### ISSUE TITLE
启用该模组重启后会导致safetyNet检测不通过

### ISSUE THREAD

**Issue by remixMe** [wuxianlin/ColorOSMagisk#2]
![011415dqijki867756w6g8](https://user-images.githubusercontent.com/36897416/114256251-b3086180-99ea-11eb-94ff-516dc98826a6.jpg)

**Comment by wuxianlin** [comment]
resetprop ro.boot.flash.locked 1

**Comment by remixMe** [comment]
这样会让我的设备上锁吗？

**Comment by remixMe** [comment]
![QQ20210411-0](https://user-images.githubusercontent.com/36897416/114288828-08a14480-9aa5-11eb-9391-c2ebe0a903b9.jpg)
我用MagiskHide Props Config设置了两个custom prop，分别在两个时间把ro.boot.flash.locked设置为0和1，可以兼顾指纹和safetynet检测。

**Comment by remixMe** [comment]
作者是否可以更新一下模组，在系统启动完了后把ro.boot.flash.locked改回1
